### PR TITLE
Janelia soma detection experiment

### PR DESCRIPTION
**Pull request by FelixChihTing**
This folder includes:
1. the application results (in spread sheet) of the [simple soma detector](https://github.com/neurodata/brainlit/blob/develop/brainlit/algorithms/detect_somas/detect.py)
2. scripts used to download the soma bounding box information and to test the find_soma function

### CODE REVIEW

**Review by tathey1 — CHANGES_REQUESTED** [review]
please add a markdown or text file summarizing what this folder is for, and what each python file does.

**Comment by FelixChihTing** [comment]
added a [notebook](https://github.com/neurodata/brainlit/blob/CTtestsoma/experiments/Janelia_soma_detection/folderdiscription.ipynb)

**Comment by FelixChihTing** [comment]
I just replaced the notebook with a [markdown](https://github.com/neurodata/brainlit/blob/CTtestsoma/experiments/Janelia_soma_detection/FolderDisc.md).

**Review by tathey1 — APPROVED** [review]
looks good

**Pull request merged**
