### PR TITLE
Fixing docs for uploading_benchmarking and downloading_benchmarking

### PR DESCRIPTION
**Pull request by shreyasingh1**
PR to fix docs for uploading_benchmarking.ipynb and downloading_benchmarking.ipynb.

Also modified the variable definition section of uploading_benchmarking.ipynb, and incorporated nbscreenshot into downloading_benchmarking.ipynb whenever napari is called.

With regards to where uploading_benchmarking.ipynb is writing to - the notebook does overwrite current files on S3. I added in a line to specify this. However, I don't think new users would be able to easily overwrite our data since they can't upload without having the proper local file structure. The upload destination in uploading_benchmarking.ipynb also corresponds to where downloading_benchmarking.ipynb looks to download data from S3.

### CODE REVIEW

**Comment by shreyasingh1** [comment]
Docs preview [here](https://deploy-preview-277--brainlit.netlify.app/). They appear to build properly!

**Comment by tathey1** [comment]
@shreyasingh1 try `git checkout develop; git pull; git checkout shreya-docs; git merge develop`

**Comment by shreyasingh1** [comment]
@tathey1 had a few initial problems with the merge but everything should be good now! and the docs look to be building correctly. Preview [here](https://deploy-preview-277--brainlit.netlify.app/tutorial.html)

**Comment by tathey1** [comment]
Hmm, if you look in files changed, it seems like this PR would undo a lot of recent updates. Do you think you could change things so the only files changed are your notebooks? There are probably more elegant ways, but the manual way is to delete those files that you don't want to change from your branch and replace them with the ones from the develop branch.

**Pull request closed without merging**
