### PR TITLE
Add registration subpackage and corresponding demo

### PR DESCRIPTION
**Pull request by DevinCrowley**
Still tweaking things with a focus on making the demo work nicely (docs/notebooks/registration_demo.ipynb) but quality of the registration itself aside it is ready for judgement.

### CODE REVIEW

**Comment by DevinCrowley** [comment]
Updated some defaults and retuned the registration in the demo, have at it!

**Comment by bvarjavand** [comment]
Cool! I'll take care of it after I fix these travis errors.

**Comment by tathey1** [comment]
@DevinCrowley is there any code in particular you'd like me to look at? the tutorial works so i trust it and would be willing to merge (after @bvarjavand fixes travis errors?)

**Comment by tathey1** [comment]
@DevinCrowley Could you please add a couple sentences to the home directory README, in the Features section, summarizing what ardent is/does (literature reference), linking the tutorial. Bijan and I think this is the last thing before a merge.

**Comment by DevinCrowley** [comment]
> @DevinCrowley Could you please add a couple sentences to the home directory README, in the Features section, summarizing what ardent is/does (including literature reference maybe), linking the tutorial. I think this is the last thing before a merge.

I've just added a subsection about the registration subpackage with references to the relevant papers. Look good?

**Pull request merged**
